// Generated by gencpp from file costmap_display/GetApproachingPoseResponse.msg
// DO NOT EDIT!


#ifndef COSTMAP_DISPLAY_MESSAGE_GETAPPROACHINGPOSERESPONSE_H
#define COSTMAP_DISPLAY_MESSAGE_GETAPPROACHINGPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int8.h>
#include <geometry_msgs/Pose2D.h>

namespace costmap_display
{
template <class ContainerAllocator>
struct GetApproachingPoseResponse_
{
  typedef GetApproachingPoseResponse_<ContainerAllocator> Type;

  GetApproachingPoseResponse_()
    : index()
    , app_pose()  {
    }
  GetApproachingPoseResponse_(const ContainerAllocator& _alloc)
    : index(_alloc)
    , app_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int8_<ContainerAllocator>  _index_type;
  _index_type index;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _app_pose_type;
  _app_pose_type app_pose;





  typedef boost::shared_ptr< ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetApproachingPoseResponse_

typedef ::costmap_display::GetApproachingPoseResponse_<std::allocator<void> > GetApproachingPoseResponse;

typedef boost::shared_ptr< ::costmap_display::GetApproachingPoseResponse > GetApproachingPoseResponsePtr;
typedef boost::shared_ptr< ::costmap_display::GetApproachingPoseResponse const> GetApproachingPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator1> & lhs, const ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.app_pose == rhs.app_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator1> & lhs, const ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace costmap_display

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d224691895890b8c7eb60427e943dcea";
  }

  static const char* value(const ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd224691895890b8cULL;
  static const uint64_t static_value2 = 0x7eb60427e943dceaULL;
};

template<class ContainerAllocator>
struct DataType< ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "costmap_display/GetApproachingPoseResponse";
  }

  static const char* value(const ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int8 index\n"
"geometry_msgs/Pose2D app_pose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int8\n"
"int8 data\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.app_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetApproachingPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::costmap_display::GetApproachingPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    s << std::endl;
    Printer< ::std_msgs::Int8_<ContainerAllocator> >::stream(s, indent + "  ", v.index);
    s << indent << "app_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.app_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COSTMAP_DISPLAY_MESSAGE_GETAPPROACHINGPOSERESPONSE_H
