// Generated by gencpp from file costmap_display/GetApproachingPose.msg
// DO NOT EDIT!


#ifndef COSTMAP_DISPLAY_MESSAGE_GETAPPROACHINGPOSE_H
#define COSTMAP_DISPLAY_MESSAGE_GETAPPROACHINGPOSE_H

#include <ros/service_traits.h>


#include <social_navigation_layers/GetApproachingPoseRequest.h>
#include <social_navigation_layers/GetApproachingPoseResponse.h>


namespace costmap_display
{

struct GetApproachingPose
{

typedef GetApproachingPoseRequest Request;
typedef GetApproachingPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetApproachingPose
} // namespace costmap_display


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::costmap_display::GetApproachingPose > {
  static const char* value()
  {
    return "d224691895890b8c7eb60427e943dcea";
  }

  static const char* value(const ::costmap_display::GetApproachingPose&) { return value(); }
};

template<>
struct DataType< ::costmap_display::GetApproachingPose > {
  static const char* value()
  {
    return "costmap_display/GetApproachingPose";
  }

  static const char* value(const ::costmap_display::GetApproachingPose&) { return value(); }
};


// service_traits::MD5Sum< ::costmap_display::GetApproachingPoseRequest> should match
// service_traits::MD5Sum< ::costmap_display::GetApproachingPose >
template<>
struct MD5Sum< ::costmap_display::GetApproachingPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::costmap_display::GetApproachingPose >::value();
  }
  static const char* value(const ::costmap_display::GetApproachingPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::costmap_display::GetApproachingPoseRequest> should match
// service_traits::DataType< ::costmap_display::GetApproachingPose >
template<>
struct DataType< ::costmap_display::GetApproachingPoseRequest>
{
  static const char* value()
  {
    return DataType< ::costmap_display::GetApproachingPose >::value();
  }
  static const char* value(const ::costmap_display::GetApproachingPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::costmap_display::GetApproachingPoseResponse> should match
// service_traits::MD5Sum< ::costmap_display::GetApproachingPose >
template<>
struct MD5Sum< ::costmap_display::GetApproachingPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::costmap_display::GetApproachingPose >::value();
  }
  static const char* value(const ::costmap_display::GetApproachingPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::costmap_display::GetApproachingPoseResponse> should match
// service_traits::DataType< ::costmap_display::GetApproachingPose >
template<>
struct DataType< ::costmap_display::GetApproachingPoseResponse>
{
  static const char* value()
  {
    return DataType< ::costmap_display::GetApproachingPose >::value();
  }
  static const char* value(const ::costmap_display::GetApproachingPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COSTMAP_DISPLAY_MESSAGE_GETAPPROACHINGPOSE_H
