// Generated by gencpp from file costmap_display/RecognitionState.msg
// DO NOT EDIT!


#ifndef COSTMAP_DISPLAY_MESSAGE_RECOGNITIONSTATE_H
#define COSTMAP_DISPLAY_MESSAGE_RECOGNITIONSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace costmap_display
{
template <class ContainerAllocator>
struct RecognitionState_
{
  typedef RecognitionState_<ContainerAllocator> Type;

  RecognitionState_()
    : startRecog(false)
    , isCorrect(false)  {
    }
  RecognitionState_(const ContainerAllocator& _alloc)
    : startRecog(false)
    , isCorrect(false)  {
  (void)_alloc;
    }



   typedef uint8_t _startRecog_type;
  _startRecog_type startRecog;

   typedef uint8_t _isCorrect_type;
  _isCorrect_type isCorrect;





  typedef boost::shared_ptr< ::costmap_display::RecognitionState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::costmap_display::RecognitionState_<ContainerAllocator> const> ConstPtr;

}; // struct RecognitionState_

typedef ::costmap_display::RecognitionState_<std::allocator<void> > RecognitionState;

typedef boost::shared_ptr< ::costmap_display::RecognitionState > RecognitionStatePtr;
typedef boost::shared_ptr< ::costmap_display::RecognitionState const> RecognitionStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::costmap_display::RecognitionState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::costmap_display::RecognitionState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::costmap_display::RecognitionState_<ContainerAllocator1> & lhs, const ::costmap_display::RecognitionState_<ContainerAllocator2> & rhs)
{
  return lhs.startRecog == rhs.startRecog &&
    lhs.isCorrect == rhs.isCorrect;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::costmap_display::RecognitionState_<ContainerAllocator1> & lhs, const ::costmap_display::RecognitionState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace costmap_display

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::costmap_display::RecognitionState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::costmap_display::RecognitionState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::costmap_display::RecognitionState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::costmap_display::RecognitionState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::costmap_display::RecognitionState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::costmap_display::RecognitionState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::costmap_display::RecognitionState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7ceb55574ba2c8ef31a449490b02235";
  }

  static const char* value(const ::costmap_display::RecognitionState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7ceb55574ba2c8eULL;
  static const uint64_t static_value2 = 0xf31a449490b02235ULL;
};

template<class ContainerAllocator>
struct DataType< ::costmap_display::RecognitionState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "costmap_display/RecognitionState";
  }

  static const char* value(const ::costmap_display::RecognitionState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::costmap_display::RecognitionState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool startRecog\n"
"bool isCorrect\n"
;
  }

  static const char* value(const ::costmap_display::RecognitionState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::costmap_display::RecognitionState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.startRecog);
      stream.next(m.isCorrect);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecognitionState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::costmap_display::RecognitionState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::costmap_display::RecognitionState_<ContainerAllocator>& v)
  {
    s << indent << "startRecog: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.startRecog);
    s << indent << "isCorrect: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isCorrect);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COSTMAP_DISPLAY_MESSAGE_RECOGNITIONSTATE_H
