// Generated by gencpp from file costmap_display/RobotPosition.msg
// DO NOT EDIT!


#ifndef COSTMAP_DISPLAY_MESSAGE_ROBOTPOSITION_H
#define COSTMAP_DISPLAY_MESSAGE_ROBOTPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace costmap_display
{
template <class ContainerAllocator>
struct RobotPosition_
{
  typedef RobotPosition_<ContainerAllocator> Type;

  RobotPosition_()
    : room(0)
    , goal_index(0)  {
    }
  RobotPosition_(const ContainerAllocator& _alloc)
    : room(0)
    , goal_index(0)  {
  (void)_alloc;
    }



   typedef int32_t _room_type;
  _room_type room;

   typedef int32_t _goal_index_type;
  _goal_index_type goal_index;





  typedef boost::shared_ptr< ::costmap_display::RobotPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::costmap_display::RobotPosition_<ContainerAllocator> const> ConstPtr;

}; // struct RobotPosition_

typedef ::costmap_display::RobotPosition_<std::allocator<void> > RobotPosition;

typedef boost::shared_ptr< ::costmap_display::RobotPosition > RobotPositionPtr;
typedef boost::shared_ptr< ::costmap_display::RobotPosition const> RobotPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::costmap_display::RobotPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::costmap_display::RobotPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::costmap_display::RobotPosition_<ContainerAllocator1> & lhs, const ::costmap_display::RobotPosition_<ContainerAllocator2> & rhs)
{
  return lhs.room == rhs.room &&
    lhs.goal_index == rhs.goal_index;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::costmap_display::RobotPosition_<ContainerAllocator1> & lhs, const ::costmap_display::RobotPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace costmap_display

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::costmap_display::RobotPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::costmap_display::RobotPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::costmap_display::RobotPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::costmap_display::RobotPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::costmap_display::RobotPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::costmap_display::RobotPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::costmap_display::RobotPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0f38e91d49bc817c4822869301cbd22";
  }

  static const char* value(const ::costmap_display::RobotPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0f38e91d49bc817ULL;
  static const uint64_t static_value2 = 0xc4822869301cbd22ULL;
};

template<class ContainerAllocator>
struct DataType< ::costmap_display::RobotPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "costmap_display/RobotPosition";
  }

  static const char* value(const ::costmap_display::RobotPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::costmap_display::RobotPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 room\n"
"int32 goal_index\n"
;
  }

  static const char* value(const ::costmap_display::RobotPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::costmap_display::RobotPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.room);
      stream.next(m.goal_index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::costmap_display::RobotPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::costmap_display::RobotPosition_<ContainerAllocator>& v)
  {
    s << indent << "room: ";
    Printer<int32_t>::stream(s, indent + "  ", v.room);
    s << indent << "goal_index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.goal_index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COSTMAP_DISPLAY_MESSAGE_ROBOTPOSITION_H
