local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 10.0
  publish_frequency: 10.0 
  static_map: false
  rolling_window: True
  width: 10.0
  height: 10.0
  resolution: 0.05
  plugins: 
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"} #2D obstacle
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    - {name: proxemic, type: "social_navigation_layers::ProxemicLayer"}
    - {name: passing, type: "social_navigation_layers::PassingLayer"}
    # - {name: simplelayer, type: "simple_layer_namespace::SimpleLayer"}
    - {name: human_group_layer, type: "social_navigation_layers::HumanGroupLayer"}
    - {name: human_object_layer, type: "social_navigation_layers::HumanObjectLayer"}
   
    #- {name: gridlayer, type: "simple_layer_namespace::GridLayer"}
  static_layer:
    enabled:              True
    map_topic:            "map"

  obstacles_layer:
    observation_sources: base_scan
    base_scan: {data_type: LaserScan, sensor_frame: laser, topic: /scan, clearing: true, marking: true}
     #scan

  inflation_layer:
    enabled:              True
    cost_scaling_factor:  10.0  #10.0 exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     0.5 #0.5 max. distance from an obstacle at which costs are incurred for planning paths.
  
  proxemic:
    enabled:  True #Whether to apply this plugin or not
    cutoff: 10.0 #Smallest value to publish on costmap adjustments
    amplitude: 90.0 #Amplitude of adjustments at peak
    covariance: 0.25 #Covariance of adjustments
    factor: 100.0 #Factor with which to scale the velocity
    keep_time: 0.75 #Pause before clearing leg list

  # passing:
  #   enabled:  True #Whether to apply this plugin or not
  #   cutoff: 10.0 #Smallest value to publish on costmap adjustments
  #   amplitude: 90.0 #Amplitude of adjustments at peak
  #   covariance: 0.25 #Covariance of adjustments
  #   factor: 50.0 #Factor with which to scale the velocity
  #   keep_time: 0.75 #Pause before clearing leg list
    
  human_group_layer:    
    enabled: True
  #   cutoff: 125 
  #   amplitude: 254
  #   covariance: 0.15
  #   factor: 1
  #   keep_time: 0.75

  human_object_layer:
    enabled: True
  #   cutoff: 125 
  #   amplitude: 254
  #   covariance: 0.15
  #   factor: 1
  #   keep_time: 0.75
